//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKASA
    {
        public int KASAID { get; set; }
        public string AY { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
    }
}
